### ISSUE TITLE
Milestone 3 TODO

### ISSUE THREAD

**Issue by roycezhou** [UBC-MDS/DSCI_532_group26-R#1]
- [x] Create a new github.com repo for your dashr project (Siqi)
- [x] Revise proposal/ implement the TA feedback (Siqi)
- [x] plotting in R (Siqi)
---------------------Siqi's tasks By Thursday--------------
- [x] dash with R (Jason)
---------------------Jason's tasks By Friday/Saturday-------------
- [x] Deployment on Heroku (Bruhat)
**include the link to your deployed dashboard clearly visible near the top of your README** 
- [x] Reflection (Bruhat)
- [x] Give peer feedback to another group (Bruhat)
---------------------Bruhat's tasks By Friday/Saturday-------------
